package group26.youdash.classes;
import java.time.LocalDateTime;

import org.springframework.beans.factory.annotation.Autowired;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "messages")
public class Messages {
     String messageId;
     int userId;
     String messageText;
     String timeStamp;
     private String profilePicture;
     String profilePictureKey;

    @Autowired
    private DynamoDBMapper dynamoDBMapper;

    public Messages() {}
    public Messages(String messageId, int userId, String messageText, String timeStamp) {
        this.messageId = messageId;
        this.userId = userId;
        this.messageText = messageText;
        this.timeStamp = timeStamp;
    }

    @DynamoDBHashKey(attributeName = "message_id")
    @DynamoDBAutoGeneratedKey
    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId =  messageId;
    }

    @DynamoDBAttribute(attributeName = "message_text")
    public String getMessageText() {
        return messageText;
    }

    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    @DynamoDBAttribute(attributeName = "timestamp")
    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timestamp) {
        this.timeStamp = timestamp;
    }

    @DynamoDBAttribute(attributeName = "user_id")
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "profile_picture")
     public String getProfilePicture() {
         return profilePicture;
     }

     public void setProfilePicture(String profilePicture) {
         this.profilePicture = profilePicture;
     }


     @DynamoDBAttribute(attributeName = "profilePictureKey")
    public String getProfilePictureKey() {
        return profilePictureKey;
    }

    public void setProfilePictureKey(String profilePictureKey) {
        this.profilePictureKey = profilePictureKey;
    }

}
