package group26.youdash.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.Date;

@DynamoDBTable(tableName = "DirectMessages")
public class DirectMessage {
    private String messageId;
    private Date timestamp;  // Changed back to Date
    private int senderId;
    private int receiverId;
    private String messageText;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    @DynamoDBAttribute
    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @DynamoDBAttribute
    public int getSenderId() {
        return senderId;
    }

    public void setSenderId(int senderId) {
        this.senderId = senderId;
    }

    @DynamoDBAttribute
    public int getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(int receiverId) {
        this.receiverId = receiverId;
    }

    @DynamoDBAttribute
    public String getMessageText() {
        return messageText;
    }

    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
}

