package group26.youdash.classes.YoutubeAPI;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "History")
public class VideoHistory {
    private String watchHistoryId;
    String url;
    float duration;
    String timeStamp;
    String videoName;
    int category;

    private String userID;

    public VideoHistory () {};

    public VideoHistory(String url, float duration, String videoName, int category, String userID) {
        this.url = url;
        this.duration = duration;
        this.videoName = videoName;
        timeStamp = LocalDateTime.now().toString();
        this.category = category;
    }
    @DynamoDBHashKey(attributeName = "watchHistoryId")
    @DynamoDBAutoGeneratedKey
    public String getWatchHistoryId() {
        return watchHistoryId;
    }
    public void setWatchHistoryId(String watchHistoryId) {
        this.watchHistoryId = watchHistoryId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userID-index")
    public String getUserID() {
        return userID;
    }
    public void setUserID(String userID) {
        this.userID = userID;
    }

    @DynamoDBAttribute(attributeName = "url")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @DynamoDBAttribute(attributeName = "duration")
    public float getDuration() {
        return duration;
    }

    public void setDuration(float duration) {
        this.duration = duration;
    }

    @DynamoDBAttribute(attributeName = "category")
    public int getCategory() {
        return category;
    }

    public void setCategory(int category) {
        this.category = category;
    }

    @DynamoDBAttribute(attributeName = "timeStamp")
    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    @DynamoDBAttribute(attributeName = "videoName")
    public String getVideoName() {
        return videoName;
    }

    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }
}
